on: [workflow_dispatch]
#  schedule:
#    - cron: '0 0 * * 1'
runs:
  using: 'node24'
  main: 'script.js'
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run JavaScript file
        run: node ./script.js

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'web-dead.nekoweb.org'
          nekoweb-username: 'web-dead'
          directory: 'public'
