on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  schedule:
#    - cron: '0 0 * * 1'

env:
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: setup
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22.22.0
      - run: npm install @actions/core
      - run: npm init -y
      - name: run script
        id: run_changeNamePointer
        run: node script.mjs #runs changeNamePointer
        
      - name: Get the new pointynumber
        run: echo "${{ steps.run_changeNamePointer.outputs.pointerResult }}"

      - name: Update Json File
        uses: restackio/update-json-file-action@2.1
        with:
          file: movie-night-order.json
          fields: "{\"turnPointer\": \"${{ steps.run_changeNamePointer.outputs.pointerResult }}\"}"
          
        
   # job3:
     # name: deploy2nekoweb
     # uses: indiefellas/deploy2nekoweb@main
    #  with:
       # nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
      #  nekoweb-domain: 'web-dead.nekoweb.org'
     #   nekoweb-username: 'web-dead'
      #  directory: 'public'
