on: [workflow_dispatch]
#  schedule:
#    - cron: '0 0 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - run: npm i @indiefellas/nekoweb-api
      
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run changeNamePointer script
        run: move-night-nekoweb/script.js

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'web-dead.nekoweb.org'
          nekoweb-username: 'web-dead'
          directory: 'public'
