name: Run script weekly 
on: [workflow_dispatch]
  # schedule:
    # - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: npm init -y
    - run: npm ci
    - run: npm test
    - run: node script.js
