name: Run script weekly 
on:
  schedule:
    - cron: '0 0 * * 1'
    
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

    #  - name: Run the turnOrder script
    #    run: node your-script.js
